/**
 * World Monitor Markdown Parser
 *
 * Parses World Monitor intelligence reports (generated by Arbor) from markdown
 * into structured data for database storage.
 *
 * Report structure:
 * - YAML frontmatter (date, time_window, type, generated_by, sectors)
 * - Executive Summary with severity-tagged items (🔴 CRITICAL, 🟠 HIGH, 🟡 MEDIUM, ℹ️ INFO)
 * - Key Themes & Patterns section
 * - Domain Deep-Dives (Geopolitics, Tech, Finance) with severity-tagged items
 * - Opportunities section
 * - Source Index
 */

export interface ParsedReport {
  reportDate: string;          // ISO date e.g. '2026-03-04'
  generatedAt: string;         // ISO datetime
  timeWindow: string | null;
  version: number;
  executiveSummary: string;
  keyThemes: string;
  fullMarkdown: string;
  sectors: string[];
  items: ParsedItem[];
}

export interface ParsedItem {
  severity: 'critical' | 'high' | 'medium' | 'info';
  sector: string | null;
  headline: string;
  body: string;
  sourceUrls: string[];
  relevantTickers: string[];
  section: 'executive_summary' | 'deep_dive' | 'opportunities';
}

const SEVERITY_MAP: Record<string, 'critical' | 'high' | 'medium' | 'info'> = {
  '🔴': 'critical',
  '🟠': 'high',
  '🟡': 'medium',
  'ℹ️': 'info',
};

const SECTOR_MAP: Record<string, string> = {
  'geopolitics': 'geopolitics',
  'geopolitics & conflicts': 'geopolitics',
  'tech': 'tech',
  'tech & ai': 'tech',
  'finance': 'finance',
  'finance & markets': 'finance',
};

/**
 * Parse YAML frontmatter from markdown content.
 * Simple parser — handles the specific format used by World Monitor reports.
 */
function parseFrontmatter(markdown: string): { frontmatter: Record<string, string>; body: string } {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    return { frontmatter: {}, body: markdown };
  }

  const frontmatter: Record<string, string> = {};
  const lines = match[1].split('\n');
  for (const line of lines) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();
    // Handle YAML arrays like [politics, tech, finance]
    if (value.startsWith('[') && value.endsWith(']')) {
      value = value.slice(1, -1);
    }
    frontmatter[key] = value;
  }

  return { frontmatter, body: match[2] };
}

/**
 * Extract URLs from markdown link syntax [text](url)
 */
function extractUrls(text: string): string[] {
  const urls: string[] = [];
  const regex = /\[.*?\]\((https?:\/\/[^)]+)\)/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    urls.push(match[1]);
  }
  return urls;
}

/**
 * Extract ticker symbols from text (uppercase 1-5 letter words that look like tickers)
 */
function extractTickers(text: string): string[] {
  // Common words to exclude
  const EXCLUDE = new Set([
    'THE', 'AND', 'FOR', 'ARE', 'BUT', 'NOT', 'YOU', 'ALL', 'CAN', 'HER',
    'WAS', 'ONE', 'OUR', 'OUT', 'HAS', 'HIS', 'HOW', 'MAN', 'NEW', 'NOW',
    'OLD', 'SEE', 'WAY', 'WHO', 'DID', 'GET', 'LET', 'SAY', 'SHE', 'TOO',
    'USE', 'DAY', 'MAY', 'HAD', 'OIL', 'GAS', 'WAR', 'FED', 'GDP', 'CPI',
    'ETF', 'IPO', 'CEO', 'CFO', 'COO', 'CTO', 'USD', 'EUR', 'GBP', 'JPY',
    'CIA', 'FBI', 'DOD', 'DOJ', 'SEC', 'MFA', 'DOE', 'ADP', 'ISM', 'LNG',
    'IRGC', 'NATO', 'OPEC', 'FOMC', 'THAAD', 'KOSPI', 'NIKKEI', 'IMF',
    'NFP', 'PMI', 'API', 'AWS', 'UAE', 'UK', 'US', 'EU', 'UN',
    'AI', 'LLM', 'GPU', 'CPU', 'RAM', 'SSD', 'ETH', 'BTC', 'SOL',
    'MOE', 'ESM', 'DAU', 'CRITICAL', 'HIGH', 'MEDIUM', 'INFO',
  ]);

  // Known tickers to always match
  const KNOWN_TICKERS = new Set([
    'NVDA', 'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AMD',
    'INTC', 'TSMC', 'TSM', 'KWEB', 'BABA', 'SPY', 'QQQ', 'IWM',
    'TLT', 'GLD', 'SLV', 'USO', 'XLE', 'XLF', 'XLK', 'IBIT',
  ]);

  const tickers: string[] = [];
  const words = text.match(/\b[A-Z]{2,5}\b/g) || [];
  for (const word of words) {
    if (KNOWN_TICKERS.has(word)) {
      if (!tickers.includes(word)) tickers.push(word);
    } else if (!EXCLUDE.has(word) && word.length >= 3) {
      // Only include unknown uppercase words if they appear in a financial context
      // (adjacent to $, price, shares, stock, etc.)
      // For now, skip these to avoid false positives
    }
  }
  return tickers;
}

/**
 * Detect which sector a deep-dive section belongs to
 */
function detectSector(sectionHeader: string): string | null {
  const lower = sectionHeader.toLowerCase();
  for (const [key, value] of Object.entries(SECTOR_MAP)) {
    if (lower.includes(key)) return value;
  }
  return null;
}

/**
 * Parse severity items from a block of text.
 * Items start with a severity emoji (🔴, 🟠, 🟡, ℹ️) followed by bold text.
 */
function parseSeverityItems(
  text: string,
  section: 'executive_summary' | 'deep_dive' | 'opportunities',
  defaultSector: string | null = null,
): ParsedItem[] {
  const items: ParsedItem[] = [];

  // Split by severity emojis at the start of a line or after a newline
  const itemBlocks = text.split(/(?=(?:^|\n)(?:🔴|🟠|🟡|ℹ️))/);

  for (const block of itemBlocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;

    // Detect severity
    let severity: 'critical' | 'high' | 'medium' | 'info' | null = null;
    let rest = trimmed;

    for (const [emoji, sev] of Object.entries(SEVERITY_MAP)) {
      if (trimmed.startsWith(emoji)) {
        severity = sev;
        rest = trimmed.slice(emoji.length).trim();
        break;
      }
    }

    if (!severity) continue;

    // Extract headline: bold text after severity label
    // Pattern: **LABEL: Headline Text** — body text
    // or: **Headline Text** — body text
    const headlineMatch = rest.match(/\*\*(?:CRITICAL|HIGH|MEDIUM|INFO)?:?\s*(.*?)\*\*/);
    if (!headlineMatch) continue;

    const headline = headlineMatch[1].trim();
    const bodyStartIdx = rest.indexOf('**', rest.indexOf('**') + 2) + 2;
    let body = rest.slice(bodyStartIdx).trim();

    // Remove leading dash/em-dash
    if (body.startsWith('—') || body.startsWith('–') || body.startsWith('-')) {
      body = body.slice(1).trim();
    }

    const sourceUrls = extractUrls(block);
    const relevantTickers = extractTickers(block);

    items.push({
      severity,
      sector: defaultSector,
      headline,
      body,
      sourceUrls,
      relevantTickers,
      section,
    });
  }

  return items;
}

/**
 * Parse a World Monitor markdown report into structured data.
 */
export function parseWorldMonitor(markdown: string): ParsedReport {
  const { frontmatter, body } = parseFrontmatter(markdown);

  // Parse date from frontmatter
  const dateStr = frontmatter.date || '';
  const dateObj = new Date(dateStr);
  const reportDate = dateObj.toISOString().split('T')[0];
  const generatedAt = dateObj.toISOString();
  const timeWindow = frontmatter.time_window || null;
  const version = parseInt(frontmatter.version || '1', 10);
  const sectors = (frontmatter.sectors || '')
    .split(',')
    .map((s: string) => s.trim())
    .filter(Boolean);

  // Split body into sections by ## headers
  const sections = body.split(/(?=^## )/m);

  let executiveSummary = '';
  let keyThemes = '';
  const allItems: ParsedItem[] = [];

  for (const section of sections) {
    const headerMatch = section.match(/^## (?:\d+\.\s*)?(.+)/m);
    if (!headerMatch) continue;

    const headerName = headerMatch[1].trim().toUpperCase();

    if (headerName.includes('EXECUTIVE SUMMARY')) {
      executiveSummary = section.replace(/^## .+\n+/, '').trim();
      const items = parseSeverityItems(executiveSummary, 'executive_summary');
      allItems.push(...items);
    } else if (headerName.includes('KEY THEMES') || headerName.includes('PATTERNS')) {
      keyThemes = section.replace(/^## .+\n+/, '').trim();
    } else if (headerName.includes('DEEP-DIVE') || headerName.includes('DEEP DIVE') || headerName.includes('DOMAIN')) {
      // Parse deep-dive subsections (### headers for sectors)
      const subSections = section.split(/(?=^### )/m);
      for (const subSection of subSections) {
        const subHeaderMatch = subSection.match(/^### (.+)/m);
        if (!subHeaderMatch) continue;
        const sector = detectSector(subHeaderMatch[1]);
        const subContent = subSection.replace(/^### .+\n+/, '').trim();
        const items = parseSeverityItems(subContent, 'deep_dive', sector);
        allItems.push(...items);
      }
    } else if (headerName.includes('OPPORTUNITIES') || headerName.includes('ANGLES')) {
      // Opportunities section — parse individual items
      const content = section.replace(/^## .+\n+/, '').trim();
      // Opportunities have different format: bold headers with analysis
      const subSections = content.split(/(?=^###\s)/m);
      for (const sub of subSections) {
        const subHeader = sub.match(/^### (.+)/m);
        if (subHeader) {
          // Sub-categories like "Contrarian Angles", "Coverage Gaps"
          const items = parseOpportunityItems(sub.replace(/^### .+\n+/, '').trim());
          allItems.push(...items);
        }
      }
    }
  }

  // Count severities
  const severityCounts = { critical: 0, high: 0, medium: 0, info: 0 };
  for (const item of allItems) {
    severityCounts[item.severity]++;
  }

  return {
    reportDate,
    generatedAt,
    timeWindow,
    version,
    executiveSummary,
    keyThemes,
    fullMarkdown: markdown,
    sectors,
    items: allItems,
  };
}

/**
 * Parse opportunity items which have a different format:
 * **Bold Title**
 * - Gap: ...
 * - Opportunity: ...
 * - Risk: ...
 */
function parseOpportunityItems(text: string): ParsedItem[] {
  const items: ParsedItem[] = [];
  const blocks = text.split(/(?=^\*\*[^*])/m);

  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;

    const titleMatch = trimmed.match(/^\*\*(.+?)\*\*/);
    if (!titleMatch) continue;

    const headline = titleMatch[1].trim();
    const body = trimmed.slice(titleMatch[0].length).trim();

    if (!headline || headline.length < 5) continue;

    items.push({
      severity: 'info',
      sector: null,
      headline,
      body: body.replace(/^[\n\-—–\s]+/, ''),
      sourceUrls: extractUrls(block),
      relevantTickers: extractTickers(block),
      section: 'opportunities',
    });
  }

  return items;
}

/**
 * Count severity items directly from markdown without full parse.
 * Useful for quick stats.
 */
export function countSeverities(markdown: string): { critical: number; high: number; medium: number; info: number } {
  const counts = { critical: 0, high: 0, medium: 0, info: 0 };
  const lines = markdown.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('🔴')) counts.critical++;
    else if (trimmed.startsWith('🟠')) counts.high++;
    else if (trimmed.startsWith('🟡')) counts.medium++;
    else if (trimmed.startsWith('ℹ️')) counts.info++;
  }
  return counts;
}
