/**
 * World Monitor Markdown Parser
 *
 * Parses World Monitor intelligence reports (generated by Arbor) from markdown
 * into structured data for database storage.
 *
 * Report structure:
 * - YAML frontmatter (date, time_window, type, generated_by, sectors)
 * - Executive Summary with severity-tagged items (🔴 CRITICAL, 🟠 HIGH, 🟡 MEDIUM, ℹ️ INFO)
 * - Key Themes & Patterns section
 * - Domain Deep-Dives (Geopolitics, Tech, Finance) with severity-tagged items
 * - Opportunities section
 * - Source Index
 */

export interface ParsedReport {
  reportDate: string;          // ISO date e.g. '2026-03-04'
  generatedAt: string;         // ISO datetime
  timeWindow: string | null;
  version: number;
  reportType: string;          // 'world-monitor' | 'thesis-monitor'
  executiveSummary: string;
  keyThemes: string;
  fullMarkdown: string;
  sectors: string[];
  items: ParsedItem[];
}

export interface ParsedItem {
  severity: 'critical' | 'high' | 'medium' | 'info';
  sector: string | null;
  headline: string;
  body: string;
  sourceUrls: string[];
  relevantTickers: string[];
  section: 'executive_summary' | 'deep_dive' | 'opportunities' | 'new_developments' | 'running_stories' | 'key_themes';
}

const SEVERITY_MAP: Record<string, 'critical' | 'high' | 'medium' | 'info'> = {
  '🔴': 'critical',
  '🟠': 'high',
  '🟡': 'medium',
  'ℹ️': 'info',
};

// Thesis monitor uses a different emoji set for signal assessments
const THESIS_MONITOR_SEVERITY_MAP: Record<string, 'critical' | 'high' | 'medium' | 'info'> = {
  '🟢': 'critical',   // Strong evidence / confirmed
  '🟡': 'medium',     // Partial evidence / emerging
  '⚪': 'info',        // No new evidence
  '🟠': 'high',       // Emerging concern (invalidation)
  '🔴': 'critical',   // Active threat
  '✅': 'critical',    // Confirmed
};

const SECTOR_MAP: Record<string, string> = {
  'geopolitics': 'geopolitics',
  'geopolitics & conflicts': 'geopolitics',
  'tech': 'tech',
  'tech & ai': 'tech',
  'finance': 'finance',
  'finance & markets': 'finance',
  'energy': 'energy',
  'energy & commodities': 'energy',
  'commodities': 'energy',
};

/**
 * Parse YAML frontmatter from markdown content.
 * Simple parser — handles the specific format used by World Monitor reports.
 */
function parseFrontmatter(markdown: string): { frontmatter: Record<string, string>; body: string } {
  const match = markdown.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    return { frontmatter: {}, body: markdown };
  }

  const frontmatter: Record<string, string> = {};
  const lines = match[1].split('\n');
  for (const line of lines) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;
    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();
    // Handle YAML arrays like [politics, tech, finance]
    if (value.startsWith('[') && value.endsWith(']')) {
      value = value.slice(1, -1);
    }
    frontmatter[key] = value;
  }

  return { frontmatter, body: match[2] };
}

/**
 * Extract URLs from markdown link syntax [text](url)
 */
function extractUrls(text: string): string[] {
  const urls: string[] = [];
  const regex = /\[.*?\]\((https?:\/\/[^)]+)\)/g;
  let match;
  while ((match = regex.exec(text)) !== null) {
    urls.push(match[1]);
  }
  return urls;
}

/**
 * Extract ticker symbols from text (uppercase 1-5 letter words that look like tickers)
 */
function extractTickers(text: string): string[] {
  // Common words to exclude
  const EXCLUDE = new Set([
    'THE', 'AND', 'FOR', 'ARE', 'BUT', 'NOT', 'YOU', 'ALL', 'CAN', 'HER',
    'WAS', 'ONE', 'OUR', 'OUT', 'HAS', 'HIS', 'HOW', 'MAN', 'NEW', 'NOW',
    'OLD', 'SEE', 'WAY', 'WHO', 'DID', 'GET', 'LET', 'SAY', 'SHE', 'TOO',
    'USE', 'DAY', 'MAY', 'HAD', 'OIL', 'GAS', 'WAR', 'FED', 'GDP', 'CPI',
    'ETF', 'IPO', 'CEO', 'CFO', 'COO', 'CTO', 'USD', 'EUR', 'GBP', 'JPY',
    'CIA', 'FBI', 'DOD', 'DOJ', 'SEC', 'MFA', 'DOE', 'ADP', 'ISM', 'LNG',
    'IRGC', 'NATO', 'OPEC', 'FOMC', 'THAAD', 'KOSPI', 'NIKKEI', 'IMF',
    'NFP', 'PMI', 'API', 'AWS', 'UAE', 'UK', 'US', 'EU', 'UN',
    'AI', 'LLM', 'GPU', 'CPU', 'RAM', 'SSD', 'ETH', 'BTC', 'SOL',
    'MOE', 'ESM', 'DAU', 'CRITICAL', 'HIGH', 'MEDIUM', 'INFO',
  ]);

  // Known tickers to always match
  const KNOWN_TICKERS = new Set([
    'NVDA', 'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AMD',
    'INTC', 'TSMC', 'TSM', 'KWEB', 'BABA', 'SPY', 'QQQ', 'IWM',
    'TLT', 'GLD', 'SLV', 'USO', 'XLE', 'XLF', 'XLK', 'IBIT',
    'HYPE', 'GLXY',
  ]);

  const tickers: string[] = [];
  const words = text.match(/\b[A-Z]{2,5}\b/g) || [];
  for (const word of words) {
    if (KNOWN_TICKERS.has(word)) {
      if (!tickers.includes(word)) tickers.push(word);
    } else if (!EXCLUDE.has(word) && word.length >= 3) {
      // Only include unknown uppercase words if they appear in a financial context
      // (adjacent to $, price, shares, stock, etc.)
      // For now, skip these to avoid false positives
    }
  }
  return tickers;
}

/**
 * Detect which sector a deep-dive section belongs to
 */
function detectSector(sectionHeader: string): string | null {
  const lower = sectionHeader.toLowerCase();
  for (const [key, value] of Object.entries(SECTOR_MAP)) {
    if (lower.includes(key)) return value;
  }
  return null;
}

/**
 * Parse severity items from a block of text.
 * Items start with a severity emoji (🔴, 🟠, 🟡, ℹ️) followed by bold text.
 */
function parseSeverityItems(
  text: string,
  section: ParsedItem['section'],
  defaultSector: string | null = null,
): ParsedItem[] {
  const items: ParsedItem[] = [];

  // Split by severity emojis at the start of a line or after a newline
  const itemBlocks = text.split(/(?=(?:^|\n)(?:🔴|🟠|🟡|ℹ️))/);

  for (const block of itemBlocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;

    // Detect severity
    let severity: 'critical' | 'high' | 'medium' | 'info' | null = null;
    let rest = trimmed;

    for (const [emoji, sev] of Object.entries(SEVERITY_MAP)) {
      if (trimmed.startsWith(emoji)) {
        severity = sev;
        rest = trimmed.slice(emoji.length).trim();
        break;
      }
    }

    if (!severity) continue;

    // Extract headline: bold text after severity label
    // Pattern: **LABEL: Headline Text** — body text
    // or: **Headline Text** — body text
    const headlineMatch = rest.match(/\*\*(?:CRITICAL|HIGH|MEDIUM|INFO)?:?\s*(.*?)\*\*/);
    if (!headlineMatch) continue;

    const headline = headlineMatch[1].trim();
    const bodyStartIdx = rest.indexOf('**', rest.indexOf('**') + 2) + 2;
    let body = rest.slice(bodyStartIdx).trim();

    // Remove leading dash/em-dash
    if (body.startsWith('—') || body.startsWith('–') || body.startsWith('-')) {
      body = body.slice(1).trim();
    }

    const sourceUrls = extractUrls(block);
    const relevantTickers = extractTickers(block);

    items.push({
      severity,
      sector: defaultSector,
      headline,
      body,
      sourceUrls,
      relevantTickers,
      section,
    });
  }

  return items;
}

/**
 * Parse thesis-monitor signal assessment items.
 * Format: - {emoji} **Signal statement**\n  Assessment text\n  [Source](url)
 */
function parseSignalAssessmentItems(text: string): ParsedItem[] {
  const items: ParsedItem[] = [];

  // Split by lines starting with - {emoji}
  const emojis = Object.keys(THESIS_MONITOR_SEVERITY_MAP);
  const emojiPattern = emojis.map(e => e.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  const itemBlocks = text.split(new RegExp(`(?=^- (?:${emojiPattern}))`, 'm'));

  for (const block of itemBlocks) {
    const trimmed = block.trim();
    if (!trimmed.startsWith('- ')) continue;

    const content = trimmed.slice(2).trim(); // Remove "- "

    // Detect severity from leading emoji
    let severity: 'critical' | 'high' | 'medium' | 'info' | null = null;
    let rest = content;

    for (const [emoji, sev] of Object.entries(THESIS_MONITOR_SEVERITY_MAP)) {
      if (content.startsWith(emoji)) {
        severity = sev;
        rest = content.slice(emoji.length).trim();
        break;
      }
    }

    if (!severity) continue;

    // Extract headline from **bold text**
    const headlineMatch = rest.match(/\*\*(.*?)\*\*/);
    if (!headlineMatch) continue;

    const headline = headlineMatch[1].trim();
    const bodyStartIdx = rest.indexOf('**', rest.indexOf('**') + 2) + 2;
    let body = rest.slice(bodyStartIdx).trim();

    const sourceUrls = extractUrls(block);
    const relevantTickers = extractTickers(block);

    items.push({
      severity,
      sector: null,
      headline,
      body,
      sourceUrls,
      relevantTickers,
      section: 'deep_dive', // Use deep_dive as the section for signal assessments
    });
  }

  return items;
}

/**
 * Parse a World Monitor markdown report into structured data.
 */
export function parseWorldMonitor(markdown: string): ParsedReport {
  const { frontmatter, body } = parseFrontmatter(markdown);

  // Parse date from frontmatter
  const dateStr = frontmatter.date || '';
  const dateObj = new Date(dateStr);
  const reportDate = dateObj.toISOString().split('T')[0];
  const generatedAt = dateObj.toISOString();
  const timeWindow = frontmatter.time_window || null;
  const version = parseInt(frontmatter.version || '1', 10);
  const reportType = frontmatter.type || 'world-monitor';
  const sectors = (frontmatter.sectors || '')
    .split(',')
    .map((s: string) => s.trim())
    .filter(Boolean);

  // Split body into sections by ## headers
  const sections = body.split(/(?=^## )/m);

  let executiveSummary = '';
  let keyThemes = '';
  const allItems: ParsedItem[] = [];

  for (const section of sections) {
    const headerMatch = section.match(/^## (?:\d+\.\s*)?(.+)/m);
    if (!headerMatch) continue;

    const headerName = headerMatch[1].trim().toUpperCase();
    const sectionContent = section.replace(/^## .+\n+/, '').trim();

    if (headerName.includes('NEW DEVELOPMENTS') || headerName.includes('EXECUTIVE SUMMARY')) {
      // Section 1: severity-tagged atomic items with per-item source URLs
      executiveSummary = sectionContent;
      const items = parseSeverityItems(sectionContent, 'new_developments');
      allItems.push(...items);
    } else if (headerName.includes('RUNNING STORIES') || headerName.includes('STATUS UPDATE')) {
      // Section 2: prose narrative items (no severity emojis)
      const items = parseRunningStories(sectionContent);
      allItems.push(...items);
    } else if (headerName.includes('KEY THEMES') || headerName.includes('PATTERNS')) {
      // Section 3: thematic analysis — itemize each theme
      keyThemes = sectionContent;
      const items = parseKeyThemes(sectionContent);
      allItems.push(...items);
    } else if (headerName.includes('DEEP-DIVE') || headerName.includes('DEEP DIVE') || headerName.includes('DOMAIN')) {
      // Section 4: sector deep-dives with severity-tagged items
      const subSections = section.split(/(?=^### )/m);
      for (const subSection of subSections) {
        const subHeaderMatch = subSection.match(/^### (.+)/m);
        if (!subHeaderMatch) continue;
        const sector = detectSector(subHeaderMatch[1]);
        const subContent = subSection.replace(/^### .+\n+/, '').trim();
        const items = parseSeverityItems(subContent, 'deep_dive', sector);
        allItems.push(...items);
      }
    } else if (headerName.includes('OPPORTUNITIES') || headerName.includes('GAPS') || headerName.includes('ANGLES')) {
      // Section 5: intelligence gaps + portfolio signals
      const items = parseOpportunitiesAndGaps(sectionContent);
      allItems.push(...items);
    } else if (headerName.includes('SIGNAL ASSESSMENT')) {
      // Thesis-monitor: parse signal assessment subsections
      executiveSummary = sectionContent;
      const subSections = section.split(/(?=^### )/m);
      for (const subSection of subSections) {
        const subHeaderMatch = subSection.match(/^### (.+)/m);
        if (!subHeaderMatch) continue;
        const subContent = subSection.replace(/^### .+\n+/, '').trim();
        const items = parseSignalAssessmentItems(subContent);
        allItems.push(...items);
      }
    } else if (headerName.includes('SIGNAL WATCH SUMMARY')) {
      keyThemes = sectionContent;
    }
    // Section 6 (SOURCE INDEX) intentionally skipped — URLs already captured per-item
  }

  // Deduplicate headlines (e.g., multiple "Coverage Gaps" across sectors)
  // by appending sector name when duplicates exist
  const headlineCounts = new Map<string, number>();
  for (const item of allItems) {
    headlineCounts.set(item.headline, (headlineCounts.get(item.headline) || 0) + 1);
  }
  for (const item of allItems) {
    if ((headlineCounts.get(item.headline) || 0) > 1 && item.sector) {
      item.headline = `${item.headline} (${item.sector})`;
    }
  }

  // Count severities
  const severityCounts = { critical: 0, high: 0, medium: 0, info: 0 };
  for (const item of allItems) {
    severityCounts[item.severity]++;
  }

  return {
    reportDate,
    generatedAt,
    timeWindow,
    version,
    reportType,
    executiveSummary,
    keyThemes,
    fullMarkdown: markdown,
    sectors,
    items: allItems,
  };
}

/**
 * Parse Running Stories section.
 * Format: bullet points starting with **Bold Title (context):** followed by narrative.
 * No severity emojis — these are status updates on ongoing stories.
 */
function parseRunningStories(text: string): ParsedItem[] {
  const items: ParsedItem[] = [];
  // Split by top-level bullet points starting with bold text
  const bullets = text.split(/(?=^- \*\*)/m);

  for (const bullet of bullets) {
    const trimmed = bullet.trim();
    if (!trimmed.startsWith('- **')) continue;

    const content = trimmed.slice(2).trim(); // Remove "- "
    const headlineMatch = content.match(/^\*\*(.+?)\*\*/);
    if (!headlineMatch) continue;

    const headline = headlineMatch[1].replace(/:\s*$/, '').trim();
    const bodyStartIdx = content.indexOf('**', content.indexOf('**') + 2) + 2;
    let body = content.slice(bodyStartIdx).trim();
    if (body.startsWith(':')) body = body.slice(1).trim();

    items.push({
      severity: 'info',
      sector: null,
      headline,
      body,
      sourceUrls: extractUrls(bullet),
      relevantTickers: extractTickers(bullet),
      section: 'running_stories',
    });
  }

  return items;
}

/**
 * Parse Key Themes section.
 * Format: **Theme N: Title**\n\nParagraph body
 */
function parseKeyThemes(text: string): ParsedItem[] {
  const items: ParsedItem[] = [];
  // Split by bold theme headers
  const blocks = text.split(/(?=^\*\*Theme \d+)/m);

  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;

    const headlineMatch = trimmed.match(/^\*\*(?:Theme \d+:\s*)?(.+?)\*\*/);
    if (!headlineMatch) continue;

    const headline = headlineMatch[1].trim();
    const body = trimmed.slice(headlineMatch[0].length).trim();

    if (!headline || headline.length < 5) continue;

    items.push({
      severity: 'medium',
      sector: null,
      headline,
      body,
      sourceUrls: extractUrls(block),
      relevantTickers: extractTickers(block),
      section: 'key_themes',
    });
  }

  return items;
}

/**
 * Parse Opportunities & Gaps section.
 * Format: **Intelligence Gaps:** / **Portfolio-Relevant Signals:**
 * followed by - **Bold item title** description text
 */
function parseOpportunitiesAndGaps(text: string): ParsedItem[] {
  const items: ParsedItem[] = [];

  // Split by sub-section headers like **Intelligence Gaps:** or **Portfolio-Relevant Signals:**
  const subSections = text.split(/(?=^\*\*(?:Intelligence Gaps|Portfolio-Relevant Signals|Contrarian Angles|Coverage Gaps)[^*]*\*\*)/m);

  for (const sub of subSections) {
    const trimmed = sub.trim();
    if (!trimmed) continue;

    // Detect sub-section type
    const headerMatch = trimmed.match(/^\*\*([^*]+)\*\*/);
    const sectionType = headerMatch?.[1]?.trim().replace(/:$/, '') || '';
    const isGap = sectionType.toLowerCase().includes('gap');

    // Parse bullet items within this sub-section
    const bullets = trimmed.split(/(?=^- \*\*)/m);
    for (const bullet of bullets) {
      const bt = bullet.trim();
      if (!bt.startsWith('- **')) continue;

      const content = bt.slice(2).trim();
      const titleMatch = content.match(/^\*\*(.+?)\*\*/);
      if (!titleMatch) continue;

      let headline = titleMatch[1].replace(/[.:]\s*$/, '').trim();
      const bodyStartIdx = content.indexOf('**', content.indexOf('**') + 2) + 2;
      let body = content.slice(bodyStartIdx).trim();
      if (body.startsWith('.') || body.startsWith(':')) body = body.slice(1).trim();

      if (!headline || headline.length < 5) continue;

      items.push({
        severity: isGap ? 'info' : 'medium',
        sector: null,
        headline: `${sectionType}: ${headline}`,
        body,
        sourceUrls: extractUrls(bullet),
        relevantTickers: extractTickers(bullet),
        section: 'opportunities',
      });
    }
  }

  // Fallback: if no sub-sections found, try the old format
  if (items.length === 0) {
    const blocks = text.split(/(?=^\*\*[^*])/m);
    for (const block of blocks) {
      const trimmed = block.trim();
      if (!trimmed) continue;
      const titleMatch = trimmed.match(/^\*\*(.+?)\*\*/);
      if (!titleMatch) continue;
      const headline = titleMatch[1].trim();
      const body = trimmed.slice(titleMatch[0].length).trim();
      if (!headline || headline.length < 5) continue;
      items.push({
        severity: 'info',
        sector: null,
        headline,
        body: body.replace(/^[\n\-—–\s]+/, ''),
        sourceUrls: extractUrls(block),
        relevantTickers: extractTickers(block),
        section: 'opportunities',
      });
    }
  }

  return items;
}

/**
 * Count severity items directly from markdown without full parse.
 * Useful for quick stats.
 */
export function countSeverities(markdown: string): { critical: number; high: number; medium: number; info: number } {
  const counts = { critical: 0, high: 0, medium: 0, info: 0 };
  const lines = markdown.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('🔴')) counts.critical++;
    else if (trimmed.startsWith('🟠')) counts.high++;
    else if (trimmed.startsWith('🟡')) counts.medium++;
    else if (trimmed.startsWith('ℹ️')) counts.info++;
  }
  return counts;
}
