#!/usr/bin/env tsx
/**
 * check-codex-parity — guard the two Claude→Codex skill surfaces against drift.
 *
 * Source of truth: every <name>/SKILL.md under .claude/skills/. Two consumers must track it:
 *   1. INTERACTIVE bridge — ~/.codex/skills/trade-journal-workflows/ (what a Codex session reads).
 *   2. HEADLESS mirror — in-repo .agents/skills/ (skill.json + SKILL.md per skill, for cron/autonomous
 *      Codex runs; regenerated by scripts/ops/generate-agents-mirror.ts).
 * Drift here = Codex silently loses (or hallucinates) a capability — the failure that left the
 * loose-agent family invisible until 2026-06-25. See the codex-interop-parity memory.
 *
 * Gate (fails, exit 1) — only for a surface that is actually present on this machine:
 *   - Bridge: claude-inventory.md must mention every skill; the three bridge files must exist;
 *     no bridge file may reference a KNOWN_REMOVED_SKILLS name.
 *   - Mirror: every skill must have .agents/skills/<n>/{skill.json,SKILL.md}, and the mirrored
 *     SKILL.md must match the current source body (stale → re-run the generator).
 * Informational (never fails): per-skill coverage of the two CURATED bridge docs (workflow-map.md,
 *   SKILL.md), which legitimately group/omit some skills.
 * An absent surface (pure-Claude machine / no mirror) is skipped, not failed.
 *
 * Usage:
 *   npx tsx scripts/ops/check-codex-parity.ts               # full report; gates on BOTH surfaces
 *   npx tsx scripts/ops/check-codex-parity.ts --json        # structured (for CI)
 *   npx tsx scripts/ops/check-codex-parity.ts --nudge        # one line iff drift, silent when clean; exit 0 (SessionStart)
 *   npx tsx scripts/ops/check-codex-parity.ts --bridge-only  # gate ONLY on the bridge; mirror staleness = warning (pre-commit)
 */
import { readdirSync, existsSync, readFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { splitFrontmatter } from '../lib/skillBody.js';

// repo root = two levels up from scripts/ops/ — resolved from the script's own location so
// the check works regardless of cwd.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const CLAUDE_SKILLS_DIR = join(REPO_ROOT, '.claude', 'skills');
const AGENTS_SKILLS_DIR = join(REPO_ROOT, '.agents', 'skills');
const BRIDGE_DIR = join(homedir(), '.codex', 'skills', 'trade-journal-workflows');

// Bridge files: the inventory is the canonical exhaustive index (GATE); the other two are
// curated routing docs (informational coverage only).
const INVENTORY = join(BRIDGE_DIR, 'references', 'claude-inventory.md');
const WORKFLOW_MAP = join(BRIDGE_DIR, 'references', 'workflow-map.md');
const BRIDGE_SKILL = join(BRIDGE_DIR, 'SKILL.md');

// Skills intentionally absent from the CURATED docs (workflow-map / SKILL.md) — archived,
// retired, or deprecated skills still belong in the exhaustive inventory but need no routing.
const RETIRED_OR_DEPRECATED = new Set(['configure-signal', 'paperclip-backlog']);
const isArchived = (name: string) => name.startsWith('archived-');
// Pipeline stages are conventionally referenced as a range ("stage-1…5"), not individually —
// exclude them from curated-coverage expectations to avoid crying wolf on intentional grouping.
const isPipelineStage = (name: string) => name.startsWith('stage-');
const isCuratedExpected = (name: string) =>
  !isArchived(name) && !RETIRED_OR_DEPRECATED.has(name) && !isPipelineStage(name);

// Skills that were removed/renamed — add a name here when you delete a skill dir, so the check
// fails until every bridge file stops referencing it. (Empty today: retired/archived skills
// still have live dirs, so the forward gate already covers them.)
const KNOWN_REMOVED_SKILLS: string[] = [];

function parseArgs(argv: string[]): Record<string, boolean> {
  const a: Record<string, boolean> = {};
  for (const x of argv) if (x.startsWith('--')) a[x.slice(2)] = true;
  return a;
}

/** Skill dirs = any immediate subdir of .claude/skills/ that contains a SKILL.md. */
function listSkills(): string[] {
  return readdirSync(CLAUDE_SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(CLAUDE_SKILLS_DIR, d.name, 'SKILL.md')))
    .map((d) => d.name)
    .sort();
}

/**
 * Does `text` mention skill `name` as a backtick token — `` `name` `` or `` `name/...` ``
 * (e.g. `decisions/SKILL.md`)? Backtick-scoping avoids matching `thesis` inside `thesis-observe`.
 */
function mentions(text: string, name: string): boolean {
  // escape hyphens are literal in a char-class-free pattern; skill names are [a-z0-9-] only.
  const re = new RegExp('`' + name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(?:`|/)');
  return re.test(text);
}

function read(path: string): string {
  return existsSync(path) ? readFileSync(path, 'utf8') : '';
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  if (!existsSync(CLAUDE_SKILLS_DIR)) {
    console.error(`No .claude/skills/ at ${CLAUDE_SKILLS_DIR} — run from the trade-journal repo.`);
    process.exit(1);
  }

  const skills = listSkills();
  const curated = skills.filter(isCuratedExpected);

  // ── Surface 1: interactive bridge (~/.codex, external — skip if this machine has no Codex) ──
  const bridgeFound = existsSync(BRIDGE_DIR);
  let filesMissing: string[] = [];
  let inventoryMissing: string[] = [];
  let workflowAbsent: string[] = [];
  let skillAbsent: string[] = [];
  let removedStillReferenced: string[] = [];
  if (bridgeFound) {
    filesMissing = [INVENTORY, WORKFLOW_MAP, BRIDGE_SKILL].filter((f) => !existsSync(f));
    const inventoryText = read(INVENTORY);
    const workflowText = read(WORKFLOW_MAP);
    const skillText = read(BRIDGE_SKILL);
    inventoryMissing = skills.filter((s) => !mentions(inventoryText, s)); // GATE: exhaustive index
    workflowAbsent = curated.filter((s) => !mentions(workflowText, s));   // INFO: curated coverage
    skillAbsent = curated.filter((s) => !mentions(skillText, s));         // INFO
    removedStillReferenced = KNOWN_REMOVED_SKILLS.filter(
      (s) => mentions(inventoryText, s) || mentions(workflowText, s) || mentions(skillText, s),
    );
  }
  const bridgeOk = !bridgeFound ||
    (filesMissing.length === 0 && inventoryMissing.length === 0 && removedStillReferenced.length === 0);

  // ── Surface 2: headless mirror (.agents/, in-repo — skip if not present) ──
  const mirrorFound = existsSync(AGENTS_SKILLS_DIR);
  const mirrorMissing: string[] = []; // no dir / no skill.json / no SKILL.md
  const mirrorStale: string[] = [];   // mirrored SKILL.md != current source body
  if (mirrorFound) {
    for (const s of skills) {
      const dst = join(AGENTS_SKILLS_DIR, s);
      if (!existsSync(join(dst, 'skill.json')) || !existsSync(join(dst, 'SKILL.md'))) { mirrorMissing.push(s); continue; }
      const expected = splitFrontmatter(read(join(CLAUDE_SKILLS_DIR, s, 'SKILL.md'))).body;
      if (read(join(dst, 'SKILL.md')) !== expected) mirrorStale.push(s);
    }
  }
  const mirrorOk = !mirrorFound || (mirrorMissing.length === 0 && mirrorStale.length === 0);

  const ok = bridgeOk && mirrorOk;

  // --bridge-only: gate ONLY on the bridge — the rare, high-value "a NEW skill is invisible to
  // interactive Codex" case. Mirror staleness becomes a non-blocking warning, so routine skill-body
  // edits aren't taxed while the headless cron fallback is still "if and when". The pre-commit uses this.
  const bridgeOnly = !!args['bridge-only'];
  const gatingOk = bridgeOnly ? bridgeOk : ok;

  // --nudge: a SessionStart reminder — one line iff drift, silent when clean. Never fails (exit 0).
  if (args.nudge) {
    if (!ok) {
      const parts: string[] = [];
      const bridgeN = inventoryMissing.length + filesMissing.length + removedStillReferenced.length;
      const mirrorN = mirrorMissing.length + mirrorStale.length;
      if (bridgeN) parts.push(`${bridgeN} bridge`);
      if (mirrorN) parts.push(`${mirrorN} mirror`);
      console.log(`[trade-journal] ⚠️ Codex skill drift (${parts.join(' · ')}) → npx tsx scripts/ops/check-codex-parity.ts`);
    }
    process.exit(0);
  }

  if (args.json) {
    console.log(JSON.stringify({
      ok,
      source: { count: skills.length, skills },
      bridge: bridgeFound ? {
        filesMissing: filesMissing.map((f) => f.replace(homedir(), '~')),
        inventoryMissing,
        workflowMapAbsentCurated: workflowAbsent,
        skillMdAbsentCurated: skillAbsent,
        curatedCount: curated.length,
        removedStillReferenced,
      } : null,
      mirror: mirrorFound ? { missing: mirrorMissing, stale: mirrorStale } : null,
      bridgeOnly,
      gatingOk,
    }, null, 2));
    process.exit(gatingOk ? 0 : 1);
  }

  console.log(`\n=== Codex ↔ Claude skill parity ===`);
  console.log(`Source: ${skills.length} skills in .claude/skills/\n`);

  // Interactive bridge
  if (!bridgeFound) {
    console.log(`bridge (~/.codex) .......... ⊘ not on this machine (skipped)`);
  } else {
    if (filesMissing.length) {
      console.log(`bridge files ............... ❌ MISSING: ${filesMissing.map((f) => f.replace(homedir(), '~')).join(', ')}`);
    }
    console.log(inventoryMissing.length === 0
      ? `claude-inventory.md ........ ✅ ${skills.length}/${skills.length} skills listed`
      : `claude-inventory.md ........ ❌ ${inventoryMissing.length} MISSING: ${inventoryMissing.join(', ')}`);
    const cov = (absent: string[]) => `${curated.length - absent.length}/${curated.length} active routed` +
      (absent.length ? ` (absent: ${absent.join(', ')})` : '');
    console.log(`workflow-map.md (curated) .. ℹ️  ${cov(workflowAbsent)}`);
    console.log(`SKILL.md (curated) ......... ℹ️  ${cov(skillAbsent)}`);
    if (removedStillReferenced.length) console.log(`removed-but-referenced ..... ❌ ${removedStillReferenced.join(', ')}`);
  }

  // Headless mirror
  if (!mirrorFound) {
    console.log(`.agents/ mirror ............ ⊘ not present (skipped)`);
  } else if (mirrorMissing.length === 0 && mirrorStale.length === 0) {
    console.log(`.agents/ mirror ............ ✅ ${skills.length}/${skills.length} current`);
  } else {
    const bits: string[] = [];
    if (mirrorMissing.length) bits.push(`${mirrorMissing.length} missing: ${mirrorMissing.join(', ')}`);
    if (mirrorStale.length) bits.push(`${mirrorStale.length} stale: ${mirrorStale.join(', ')}`);
    // ⚠️ (non-gating) under --bridge-only, ❌ (gating) otherwise.
    console.log(`.agents/ mirror ............ ${bridgeOnly ? '⚠️ ' : '❌'} ${bits.join('; ')}${bridgeOnly ? ' (warning — not gated)' : ''}`);
  }

  if (ok) {
    console.log(`\n✅ In sync — no gating drift.`);
    if (bridgeFound && (workflowAbsent.length || skillAbsent.length)) {
      console.log(`   (ℹ️ curated-doc omissions above are informational — add routing if a skill warrants it.)`);
    }
  } else if (gatingOk) {
    // --bridge-only: bridge is clean; mirror drift is reported as a warning, not a failure.
    console.log(`\n✅ Bridge in sync. ⚠️ Mirror drift is a warning here (--bridge-only), not a block.`);
    console.log(`   Regenerate when convenient: npx tsx scripts/ops/generate-agents-mirror.ts && git add .agents`);
  } else {
    console.log(`\n✗ Drift detected:`);
    if (inventoryMissing.length) console.log(`   - add ${inventoryMissing.join(', ')} to the bridge references/claude-inventory.md`);
    if (removedStillReferenced.length) console.log(`   - remove stale bridge refs to ${removedStillReferenced.join(', ')} (and clear KNOWN_REMOVED_SKILLS once done)`);
    if (filesMissing.length) console.log(`   - restore the missing bridge file(s) above`);
    if (mirrorMissing.length || mirrorStale.length) console.log(`   - regenerate the mirror: npx tsx scripts/ops/generate-agents-mirror.ts`);
  }
  process.exit(gatingOk ? 0 : 1);
}

main();
