'use client';

/**
 * Convert Claim To Entity Dialog
 *
 * Allows converting a main claim into a new Macro Thesis or Asset View.
 * The claim is NOT converted itself - it remains as evidence linked to the new entity.
 *
 * Part of Phase 2.6.5: Streamlined Claim Conversion
 */

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { SectorSelector } from '@/components/ui/SectorSelector';
import type { MainClaim } from '@/db/schema';

interface ConvertClaimToEntityDialogProps {
  claim: MainClaim;
  isOpen: boolean;
  onClose: () => void;
}

type EntityType = 'macro_thesis' | 'asset_view';
type Direction = 'bullish' | 'bearish' | 'neutral';
type TimeHorizon = 'long_term' | 'medium_term' | 'short_term';
type ThesisType = 'secular' | 'cyclical' | 'structural';

export function ConvertClaimToEntityDialog({
  claim,
  isOpen,
  onClose,
}: ConvertClaimToEntityDialogProps) {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Step 1: Choose entity type
  const [entityType, setEntityType] = useState<EntityType | null>(null);

  // Common fields
  const [direction, setDirection] = useState<Direction | ''>('');
  const [timeHorizon, setTimeHorizon] = useState<TimeHorizon | ''>('');
  const [confidenceLevel, setConfidenceLevel] = useState<string>('medium');

  // Macro Thesis specific fields
  const [thesisType, setThesisType] = useState<ThesisType>('cyclical');
  const [sectors, setSectors] = useState<string[]>([]);

  // Asset View specific fields
  const [ticker, setTicker] = useState('');

  // Auto-generate title based on selections
  const getGeneratedTitle = (): string => {
    if (entityType === 'macro_thesis') {
      const parts = [];
      if (direction) parts.push(direction.charAt(0).toUpperCase() + direction.slice(1));
      if (sectors.length > 0) parts.push(sectors[0]);
      if (timeHorizon) parts.push(timeHorizon.replace('_', ' '));
      return parts.length > 0 ? parts.join(' ') : 'Untitled Macro Thesis';
    } else if (entityType === 'asset_view') {
      const parts = [];
      if (direction) parts.push(direction.charAt(0).toUpperCase() + direction.slice(1));
      if (ticker) parts.push(ticker.toUpperCase());
      if (timeHorizon) parts.push(timeHorizon.replace('_', ' '));
      return parts.length > 0 ? parts.join(' ') : 'Untitled Asset View';
    }
    return '';
  };

  const handleSubmit = async () => {
    setError(null);
    setIsSubmitting(true);

    try {
      if (entityType === 'macro_thesis') {
        // Create Macro Thesis
        const response = await fetch('/api/theses/create', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            // Title will be auto-generated by API
            thesisType,
            direction: direction || null,
            sectors,
            timeHorizon: timeHorizon || null,
            confidenceLevel,
            status: 'active',
            description: `Created from claim: ${claim.claim}`,
            linkedMainClaimIds: [claim.id], // Link the claim as evidence
            notes: {
              source_claim_id: claim.id,
              source_claim_title: claim.title,
              created_via_conversion: true,
            },
          }),
        });

        if (!response.ok) {
          const data = await response.json();
          throw new Error(data.error || 'Failed to create macro thesis');
        }

        const data = await response.json();
        router.push(`/theses/${data.thesisId}`);
        router.refresh();
        onClose();
      } else if (entityType === 'asset_view') {
        // Validate ticker
        if (!ticker) {
          setError('Ticker is required for Asset Views');
          setIsSubmitting(false);
          return;
        }

        // Create Asset View
        const response = await fetch('/api/asset-views/create', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            // Title will be auto-generated by API
            ticker,
            viewType: direction || 'neutral', // Map direction to viewType
            direction: direction || null,
            timeHorizon: timeHorizon || null,
            confidenceLevel,
            status: 'active',
            description: `Created from claim: ${claim.claim}`,
            linkedMainClaimIds: [claim.id], // Link the claim as evidence
            notes: {
              source_claim_id: claim.id,
              source_claim_title: claim.title,
              created_via_conversion: true,
            },
          }),
        });

        if (!response.ok) {
          const data = await response.json();
          throw new Error(data.error || 'Failed to create asset view');
        }

        const data = await response.json();
        router.push(`/asset-views/${data.viewId}`);
        router.refresh();
        onClose();
      }
    } catch (err) {
      console.error('Error converting claim:', err);
      setError(err instanceof Error ? err.message : 'Unknown error occurred');
      setIsSubmitting(false);
    }
  };

  const resetForm = () => {
    setEntityType(null);
    setDirection('');
    setTimeHorizon('');
    setConfidenceLevel('medium');
    setThesisType('cyclical');
    setSectors([]);
    setTicker('');
    setError(null);
  };

  const handleClose = () => {
    resetForm();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-slate-200 p-6">
          <h2 className="text-2xl font-semibold">Convert Claim to Thesis/View</h2>
          <p className="text-sm text-slate-600 mt-1">
            Create a new Macro Thesis or Asset View from this claim
          </p>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          {/* Show claim being converted */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h3 className="text-sm font-semibold text-blue-900 mb-2">Claim</h3>
            <p className="text-sm text-blue-800">{claim.claim}</p>
            {claim.qualifier && (
              <span className="inline-flex px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded mt-2">
                {claim.qualifier} confidence
              </span>
            )}
          </div>

          {/* Step 1: Choose Entity Type */}
          {!entityType && (
            <div className="space-y-3">
              <h3 className="font-medium">What would you like to create?</h3>
              <div className="grid grid-cols-2 gap-4">
                <button
                  onClick={() => setEntityType('macro_thesis')}
                  className="p-6 border-2 border-slate-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition-colors text-left"
                >
                  <div className="font-semibold text-lg mb-2">Macro Thesis</div>
                  <div className="text-sm text-slate-600">
                    Cross-asset belief (secular, cyclical, or structural)
                  </div>
                </button>
                <button
                  onClick={() => setEntityType('asset_view')}
                  className="p-6 border-2 border-slate-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition-colors text-left"
                >
                  <div className="font-semibold text-lg mb-2">Asset View</div>
                  <div className="text-sm text-slate-600">
                    Asset-specific thesis about a particular underlying
                  </div>
                </button>
              </div>
            </div>
          )}

          {/* Step 2: Fill in fields */}
          {entityType && (
            <div className="space-y-6">
              {/* Preview generated title */}
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-slate-700 mb-2">
                  Generated Title (preview)
                </h3>
                <p className="text-lg font-medium text-slate-900">
                  {getGeneratedTitle()}
                </p>
              </div>

              {/* Common Fields */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  Direction
                </label>
                <select
                  value={direction}
                  onChange={(e) => setDirection(e.target.value as Direction | '')}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg"
                >
                  <option value="">Select direction...</option>
                  <option value="bullish">Bullish</option>
                  <option value="bearish">Bearish</option>
                  <option value="neutral">Neutral</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  Time Horizon
                </label>
                <select
                  value={timeHorizon}
                  onChange={(e) => setTimeHorizon(e.target.value as TimeHorizon | '')}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg"
                >
                  <option value="">Select time horizon...</option>
                  <option value="long_term">Long Term</option>
                  <option value="medium_term">Medium Term</option>
                  <option value="short_term">Short Term</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-2">
                  Confidence Level
                </label>
                <select
                  value={confidenceLevel}
                  onChange={(e) => setConfidenceLevel(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg"
                >
                  <option value="high">High</option>
                  <option value="medium">Medium</option>
                  <option value="low">Low</option>
                  <option value="exploratory">Exploratory</option>
                </select>
              </div>

              {/* Macro Thesis Specific Fields */}
              {entityType === 'macro_thesis' && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Thesis Type
                    </label>
                    <select
                      value={thesisType}
                      onChange={(e) => setThesisType(e.target.value as ThesisType)}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg"
                    >
                      <option value="secular">Secular</option>
                      <option value="cyclical">Cyclical</option>
                      <option value="structural">Structural</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-2">
                      Sectors / Topics <span className="text-red-500">*</span>
                    </label>
                    <SectorSelector value={sectors} onChange={setSectors} />
                    {sectors.length === 0 && (
                      <p className="text-xs text-slate-500 mt-1">
                        At least one sector is required for auto-generated titles
                      </p>
                    )}
                  </div>
                </>
              )}

              {/* Asset View Specific Fields */}
              {entityType === 'asset_view' && (
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">
                    Ticker <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={ticker}
                    onChange={(e) => setTicker(e.target.value.toUpperCase())}
                    placeholder="e.g., TSLA"
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg font-mono uppercase"
                  />
                  <p className="text-xs text-slate-500 mt-1">
                    Ticker must exist in the underlyings table
                  </p>
                </div>
              )}
            </div>
          )}

          {/* Error Message */}
          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-sm text-red-800">{error}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-white border-t border-slate-200 p-6 flex justify-between">
          <div>
            {entityType && (
              <Button variant="ghost" onClick={() => setEntityType(null)}>
                ← Back
              </Button>
            )}
          </div>
          <div className="flex gap-3">
            <Button variant="ghost" onClick={handleClose} disabled={isSubmitting}>
              Cancel
            </Button>
            {entityType && (
              <Button onClick={handleSubmit} disabled={isSubmitting}>
                {isSubmitting ? 'Creating...' : `Create ${entityType === 'macro_thesis' ? 'Macro Thesis' : 'Asset View'}`}
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
