'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { ResearchInsight } from '@/db/schema';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

interface InsightReviewProps {
  insight: ResearchInsight;
  artifactId: string;
}

export function InsightReview({ insight, artifactId }: InsightReviewProps) {
  const router = useRouter();
  const [editing, setEditing] = useState(false);
  const [notes, setNotes] = useState(insight.humanReviewNotes || '');
  const [saving, setSaving] = useState(false);

  const handleApprove = async () => {
    setSaving(true);
    try {
      const response = await fetch('/api/research/insights', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: insight.id,
          humanReviewed: true,
          humanReviewNotes: notes,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to approve insight');
      }

      router.refresh();
    } catch (error) {
      console.error('Error approving insight:', error);
    } finally {
      setSaving(false);
      setEditing(false);
    }
  };

  const keyClaims = (insight.keyClaims as any) || [];
  const supportingEvidence = (insight.supportingEvidence as any) || [];
  const counterEvidence = (insight.counterEvidence as any) || [];

  return (
    <div className="bg-white rounded-lg border border-slate-200 p-6">
      <div className="flex justify-between items-start mb-6">
        <div>
          <h3 className="text-lg font-semibold">AI-Generated Insights</h3>
          <p className="text-sm text-slate-500 mt-1">
            Generated by {insight.aiModel || 'AI'} •{' '}
            {insight.aiProcessingCostUsd
              ? `Cost: $${Number(insight.aiProcessingCostUsd).toFixed(4)}`
              : 'Cost unknown'}
          </p>
        </div>
        {!insight.humanReviewed && (
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setEditing(!editing)}
            >
              {editing ? 'Cancel' : 'Add Notes'}
            </Button>
            <Button size="sm" onClick={handleApprove} disabled={saving}>
              {saving ? 'Approving...' : 'Approve'}
            </Button>
          </div>
        )}
        {insight.humanReviewed && (
          <Badge className="bg-emerald-100 text-emerald-700">Reviewed</Badge>
        )}
      </div>

      {/* Summary */}
      <div className="mb-6">
        <h4 className="text-sm font-semibold text-slate-700 mb-2">Summary</h4>
        <p className="text-sm text-slate-900">{insight.summary}</p>
      </div>

      {/* Key Themes */}
      {insight.keyThemes && insight.keyThemes.length > 0 && (
        <div className="mb-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Key Themes</h4>
          <div className="flex flex-wrap gap-2">
            {insight.keyThemes.map((theme, idx) => (
              <span
                key={idx}
                className="inline-flex px-3 py-1 text-sm bg-blue-100 text-blue-700 rounded-full"
              >
                {theme}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Metadata Grid */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        {insight.timeHorizon && (
          <div>
            <h4 className="text-sm font-semibold text-slate-700 mb-1">Time Horizon</h4>
            <p className="text-sm text-slate-900 capitalize">
              {insight.timeHorizon.replace('_', ' ')}
            </p>
          </div>
        )}
        {insight.confidenceLevel && (
          <div>
            <h4 className="text-sm font-semibold text-slate-700 mb-1">Confidence</h4>
            <p className="text-sm text-slate-900 capitalize">{insight.confidenceLevel}</p>
          </div>
        )}
      </div>

      {/* Relevant Tickers */}
      {insight.relevantTickers && insight.relevantTickers.length > 0 && (
        <div className="mb-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Relevant Tickers</h4>
          <div className="flex flex-wrap gap-2">
            {insight.relevantTickers.map((ticker) => (
              <span
                key={ticker}
                className="inline-flex px-2 py-1 text-sm font-mono bg-slate-100 text-slate-900 rounded"
              >
                {ticker}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Key Claims */}
      {keyClaims.length > 0 && (
        <div className="mb-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Key Claims</h4>
          <div className="space-y-3">
            {keyClaims.map((claim: any, idx: number) => (
              <div key={idx} className="border-l-4 border-blue-500 pl-4 py-2">
                <p className="text-sm font-medium text-slate-900">{claim.claim}</p>
                {claim.evidence && (
                  <p className="text-sm text-slate-600 mt-1">{claim.evidence}</p>
                )}
                {claim.confidence && (
                  <span className="inline-flex mt-2 px-2 py-0.5 text-xs bg-slate-100 text-slate-700 rounded">
                    Confidence: {claim.confidence}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Supporting Evidence */}
      {supportingEvidence.length > 0 && (
        <div className="mb-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Supporting Evidence</h4>
          <ul className="space-y-2">
            {supportingEvidence.map((evidence: any, idx: number) => (
              <li key={idx} className="text-sm text-slate-900">
                <span className="text-emerald-600 font-medium">✓</span> {evidence.point}
                {evidence.source && (
                  <span className="text-slate-500 text-xs ml-2">({evidence.source})</span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Counter Evidence */}
      {counterEvidence.length > 0 && (
        <div className="mb-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Counter Evidence / Risks</h4>
          <ul className="space-y-2">
            {counterEvidence.map((evidence: any, idx: number) => (
              <li key={idx} className="text-sm text-slate-900">
                <span className="text-red-600 font-medium">⚠</span> {evidence.point}
                {evidence.source && (
                  <span className="text-slate-500 text-xs ml-2">({evidence.source})</span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Human Review Notes */}
      {editing && (
        <div className="mb-6 border-t pt-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Review Notes</h4>
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            rows={4}
            className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
            placeholder="Add any notes, corrections, or observations about this AI-generated insight..."
          />
        </div>
      )}

      {insight.humanReviewNotes && !editing && (
        <div className="border-t pt-6">
          <h4 className="text-sm font-semibold text-slate-700 mb-2">Review Notes</h4>
          <p className="text-sm text-slate-900 whitespace-pre-wrap">{insight.humanReviewNotes}</p>
        </div>
      )}
    </div>
  );
}
