'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Loader2 } from 'lucide-react';

interface CreateStrategyFormData {
  label?: string;
  strategyKey: string;
  description?: string;
  direction: 'long' | 'short' | 'neutral';
  status: 'open' | 'closed';
  assetThesisId?: string;
  // Note: strategies no longer have direct macroThesisId - they inherit through asset thesis
}

interface CreateStrategyFormProps {
  onSubmit: (data: CreateStrategyFormData) => Promise<void>;
  onCancel: () => void;
  initialData?: Partial<CreateStrategyFormData>;
  autoGenLabel?: boolean;
  assetThesisId?: string; // Auto-link to this asset thesis
  // Note: macroThesisId removed - strategies inherit macro thesis through asset thesis
}

export function CreateStrategyForm({
  onSubmit,
  onCancel,
  initialData = {},
  autoGenLabel = true,
  assetThesisId,
}: CreateStrategyFormProps) {
  const [formData, setFormData] = useState<CreateStrategyFormData>({
    direction: initialData.direction || 'long',
    status: initialData.status || 'open',
    strategyKey: initialData.strategyKey || '',
    label: initialData.label,
    description: initialData.description,
    assetThesisId: assetThesisId || initialData.assetThesisId,
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Validation
    if (!formData.strategyKey.trim()) {
      setError('Strategy key is required');
      return;
    }

    if (!autoGenLabel && !formData.label?.trim()) {
      setError('Label is required');
      return;
    }

    setLoading(true);
    try {
      await onSubmit(formData);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create strategy');
      setLoading(false);
    }
  };

  const getAutoGeneratedLabel = () => {
    if (!formData.strategyKey) return '';
    return `${formData.direction.toUpperCase()} ${formData.strategyKey}`;
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 p-4">
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-800">
          {error}
        </div>
      )}

      {/* Strategy Key */}
      <div>
        <label className="block text-sm font-medium text-slate-700 mb-1">
          Strategy Key <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          value={formData.strategyKey}
          onChange={(e) => setFormData({ ...formData, strategyKey: e.target.value })}
          className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          placeholder="e.g., AAPL_LEAP_2025Q4"
          required
          disabled={loading}
        />
        <p className="text-xs text-slate-500 mt-1">
          Unique identifier for this strategy (e.g., ticker_type_expiry)
        </p>
      </div>

      {/* Label (optional if auto-generated) */}
      {!autoGenLabel && (
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Label <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            value={formData.label || ''}
            onChange={(e) => setFormData({ ...formData, label: e.target.value })}
            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="e.g., LONG AAPL LEAP 2025Q4"
            required={!autoGenLabel}
            disabled={loading}
          />
        </div>
      )}

      {autoGenLabel && formData.strategyKey && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 text-sm text-blue-800">
          <strong>Note:</strong> Label will be auto-generated as: {getAutoGeneratedLabel()}
        </div>
      )}

      <div className="grid grid-cols-2 gap-4">
        {/* Direction */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Direction <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.direction}
            onChange={(e) => setFormData({ ...formData, direction: e.target.value as any })}
            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="long">Long</option>
            <option value="short">Short</option>
            <option value="neutral">Neutral</option>
          </select>
        </div>

        {/* Status */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">
            Status <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.status}
            onChange={(e) => setFormData({ ...formData, status: e.target.value as any })}
            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="open">Open</option>
            <option value="closed">Closed</option>
          </select>
        </div>
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-medium text-slate-700 mb-1">
          Description (optional)
        </label>
        <textarea
          value={formData.description || ''}
          onChange={(e) => setFormData({ ...formData, description: e.target.value })}
          className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          rows={3}
          placeholder="Brief description of the strategy..."
          disabled={loading}
        />
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          disabled={loading}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Creating...
            </>
          ) : (
            'Create & Link'
          )}
        </Button>
      </div>
    </form>
  );
}

