'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Loader2, X } from 'lucide-react';
import { 
  getAllTaxonomyItems, 
  searchTaxonomy, 
  TaxonomyItem 
} from '@/lib/constants/sector-taxonomy';

interface CreateMacroThesisFormData {
  title?: string;
  description?: string;
  thesisType: 'secular' | 'cyclical' | 'structural';
  direction: 'bullish' | 'bearish' | 'neutral';
  timeHorizon: 'long_term' | 'medium_term' | 'short_term';
  confidenceLevel: 'high' | 'medium' | 'low' | 'exploratory';
  status: 'draft' | 'developing' | 'monitoring' | 'complete' | 'rejected';
  sectors: string[];
  positionStartDate?: string;
  positionEndDate?: string;
}

interface CreateMacroThesisFormProps {
  onSubmit: (data: CreateMacroThesisFormData) => Promise<void>;
  onCancel: () => void;
  initialData?: Partial<CreateMacroThesisFormData>;
  autoGenTitle?: boolean;
}

export function CreateMacroThesisForm({
  onSubmit,
  onCancel,
  initialData = {},
  autoGenTitle = true,
}: CreateMacroThesisFormProps) {
  const [formData, setFormData] = useState<CreateMacroThesisFormData>({
    thesisType: initialData.thesisType || 'cyclical',
    direction: initialData.direction || 'neutral',
    timeHorizon: initialData.timeHorizon || 'medium_term',
    confidenceLevel: initialData.confidenceLevel || 'medium',
    status: initialData.status || 'developing',
    sectors: initialData.sectors || [],
    title: initialData.title,
    description: initialData.description,
    positionStartDate: initialData.positionStartDate,
    positionEndDate: initialData.positionEndDate,
  });

  const [sectorSearch, setSectorSearch] = useState('');
  const [showSectorDropdown, setShowSectorDropdown] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Get filtered taxonomy items
  const filteredTaxonomyItems = sectorSearch 
    ? searchTaxonomy(sectorSearch) 
    : getAllTaxonomyItems().slice(0, 20); // Show first 20 by default

  const handleAddSector = (item: TaxonomyItem) => {
    if (!formData.sectors.includes(item.value)) {
      setFormData({
        ...formData,
        sectors: [...formData.sectors, item.value],
      });
    }
    setSectorSearch('');
    setShowSectorDropdown(false);
  };

  const handleRemoveSector = (sectorValue: string) => {
    setFormData({
      ...formData,
      sectors: formData.sectors.filter((s) => s !== sectorValue),
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    // Validation
    if (!autoGenTitle && !formData.title?.trim()) {
      setError('Title is required');
      return;
    }

    setLoading(true);
    try {
      await onSubmit(formData);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create macro thesis');
      setLoading(false);
    }
  };

  const getAutoGeneratedTitle = () => {
    if (formData.sectors.length === 0) return '';
    const firstSector = formData.sectors[0].replace('Sector - ', '').replace('Theme - ', '');
    return `${formData.direction.charAt(0).toUpperCase() + formData.direction.slice(1)} ${firstSector} ${formData.timeHorizon.replace('_', ' ')}`;
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 p-4">
      {error && (
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-3 text-sm text-red-800 dark:text-red-200">
          {error}
        </div>
      )}

      {/* Title (optional if auto-generated) */}
      {!autoGenTitle && (
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Title <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            value={formData.title || ''}
            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="e.g., Physical AI Infrastructure Buildout (2025-2026)"
            required={!autoGenTitle}
            disabled={loading}
          />
        </div>
      )}

      {autoGenTitle && formData.sectors.length > 0 && (
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-3 text-sm text-blue-800 dark:text-blue-200">
          <strong>Note:</strong> Title will be auto-generated as: {getAutoGeneratedTitle()}
        </div>
      )}

      {/* Description */}
      <div>
        <label className="block text-sm font-medium text-foreground mb-1">
          Description (optional)
        </label>
        <textarea
          value={formData.description || ''}
          onChange={(e) => setFormData({ ...formData, description: e.target.value })}
          className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          rows={3}
          placeholder="Brief description of the thesis..."
          disabled={loading}
        />
      </div>

      {/* Row: Type, Horizon, Confidence */}
      <div className="grid grid-cols-3 gap-4">
        {/* Thesis Type */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Type <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.thesisType}
            onChange={(e) => setFormData({ ...formData, thesisType: e.target.value as any })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="cyclical">Cyclical</option>
            <option value="secular">Secular</option>
            <option value="structural">Structural</option>
          </select>
        </div>

        {/* Time Horizon */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Time Horizon <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.timeHorizon}
            onChange={(e) => setFormData({ ...formData, timeHorizon: e.target.value as any })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="short_term">Short Term</option>
            <option value="medium_term">Medium Term</option>
            <option value="long_term">Long Term</option>
          </select>
        </div>

        {/* Confidence Level */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Confidence <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.confidenceLevel}
            onChange={(e) => setFormData({ ...formData, confidenceLevel: e.target.value as any })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="exploratory">Exploratory</option>
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
          </select>
        </div>
      </div>

      {/* Row: Direction, Status */}
      <div className="grid grid-cols-2 gap-4">
        {/* Direction */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Direction <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.direction}
            onChange={(e) => setFormData({ ...formData, direction: e.target.value as any })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="neutral">Neutral</option>
            <option value="bullish">Bullish</option>
            <option value="bearish">Bearish</option>
          </select>
        </div>

        {/* Status */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Status <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.status}
            onChange={(e) => setFormData({ ...formData, status: e.target.value as any })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            required
            disabled={loading}
          >
            <option value="draft">Draft</option>
            <option value="developing">Developing</option>
            <option value="monitoring">Monitoring</option>
            <option value="complete">Complete</option>
            <option value="rejected">Rejected</option>
          </select>
        </div>
      </div>

      {/* Sectors (with taxonomy search) */}
      <div>
        <label className="block text-sm font-medium text-foreground mb-1">
          Sectors / Themes
        </label>
        <div className="relative">
          <input
            type="text"
            value={sectorSearch}
            onChange={(e) => {
              setSectorSearch(e.target.value);
              setShowSectorDropdown(true);
            }}
            onFocus={() => setShowSectorDropdown(true)}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Search sectors, industries, themes, regions..."
            disabled={loading}
          />
          
          {/* Dropdown with taxonomy items */}
          {showSectorDropdown && (
            <div className="absolute z-10 w-full mt-1 bg-card border rounded-lg shadow-lg max-h-60 overflow-y-auto">
              {filteredTaxonomyItems.length === 0 ? (
                <div className="p-3 text-sm text-muted-foreground text-center">
                  No matching sectors found
                </div>
              ) : (
                filteredTaxonomyItems.map((item) => (
                  <button
                    key={item.value}
                    type="button"
                    onClick={() => handleAddSector(item)}
                    className="w-full text-left px-3 py-2 hover:bg-muted border-b border-border last:border-b-0"
                    disabled={formData.sectors.includes(item.value)}
                  >
                    <div className="font-medium text-sm text-foreground">{item.label}</div>
                    {item.description && (
                      <div className="text-xs text-muted-foreground">{item.description}</div>
                    )}
                    {formData.sectors.includes(item.value) && (
                      <Badge className="mt-1 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 text-xs">Selected</Badge>
                    )}
                  </button>
                ))
              )}
            </div>
          )}
        </div>

        {/* Selected sectors */}
        {formData.sectors.length > 0 && (
          <div className="mt-2 flex flex-wrap gap-2">
            {formData.sectors.map((sectorValue) => {
              const item = getAllTaxonomyItems().find(i => i.value === sectorValue);
              return (
                <Badge
                  key={sectorValue}
                  variant="secondary"
                  className="pl-2 pr-1 py-1 text-xs"
                >
                  {item?.label || sectorValue}
                  <button
                    type="button"
                    onClick={() => handleRemoveSector(sectorValue)}
                    className="ml-1 hover:bg-muted rounded-full p-0.5"
                    disabled={loading}
                  >
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              );
            })}
          </div>
        )}
      </div>

      {/* Position Dates */}
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Position Start Date
          </label>
          <input
            type="date"
            value={formData.positionStartDate || ''}
            onChange={(e) => setFormData({ ...formData, positionStartDate: e.target.value })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            disabled={loading}
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-foreground mb-1">
            Position End Date
          </label>
          <input
            type="date"
            value={formData.positionEndDate || ''}
            onChange={(e) => setFormData({ ...formData, positionEndDate: e.target.value })}
            className="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            disabled={loading}
          />
        </div>
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3 pt-4 border-t">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          disabled={loading}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Creating...
            </>
          ) : (
            'Create & Link'
          )}
        </Button>
      </div>
    </form>
  );
}
