#!/usr/bin/env tsx

/**
 * DEPRECATED: This script used to call the Anthropic API directly.
 * Thesis linkage suggestions are now generated by Claude Code inline
 * during the /finalize-for-upload skill (see Step 5 in SKILL.md).
 *
 * For backfilling existing claims, use:
 *   npx tsx scripts/backfill-claim-suggestions.ts [--dry-run]
 * which lists unlinked claims for Claude Code to analyze.
 *
 * This script is kept for reference but should not be called.
 */

console.log('DEPRECATED: Suggestion generation is now done by Claude Code inline.');
console.log('See .claude/skills/finalize-for-upload/SKILL.md Step 5.');
console.log('For backfilling, use: npx tsx scripts/backfill-claim-suggestions.ts --dry-run');
process.exit(0);
